name: Auto Assign Issue

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign the commenter to the issue
        if: ${{ github.event.comment.body == 'assign me' }}
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.comment.user.login }}
