name: Assign Issue to Commenter
on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to commenter
        if: contains(github.event.comment.body, '/assign')
        uses: kentaro-m/auto-assign-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assign_to: ${{ github.event.comment.user.login }}
