name: Release Monitor

on: 
    workflow_dispatch:

jobs:
    check_release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
               python-version: '3.x'
    
            - name: Install dependencies
              run: |
               python -m pip install --upgrade pip
               pip install requests
    
            - name: Run script to monitor releases
              run: |
               python main.py
            
            - name: Check changes
              id: check_changes
              run: |
                if [[ $(git status --porcelain) ]]; then
                    echo "changes_detected=false"
                else
                    echo "changes_detected=true"
                fi

            - name: Commit if needed
              if: env.changes_detected == 'true'
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "update json"
                git push
            
            - name: No changes detected
              if: env.changes_detected == 'false'
              run: |
                echo "no changes detected"
