name: Release Monitor

on: 
    workflow_dispatch:

jobs:
    check_release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
               python-version: '3.x'
    
            - name: Install dependencies
              run: |
               python -m pip install --upgrade pip
               pip install requests
    
            - name: Run script to monitor releases
              run: |
               python main.py
            
            - name: Check changes
              id: check_changes
              run: |
                git diff-index --quiet HEAD
                echo "changes_detected=true" >> $GITHUB_ENV

            - name: Commit if needed
              if: env.changes_detected == 'true'
              run: |
                git add .
                git commit -m "update json"
                git push
